import os
from pathlib import Path
import dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

if os.path.isfile(BASE_DIR / ".env"):
    dotenv.load_dotenv(BASE_DIR / ".env")

data = {
    'atts[element_title]': '',
    'atts[post_type]': 'product',
    'atts[layout]': 'grid',
    'atts[include]': '',
    'atts[custom_query]': '',
    'atts[taxonomies]': '',
    'atts[pagination]': 'infinit',
    'atts[items_per_page]': '25',
    'atts[product_hover]': 'standard',
    'atts[spacing]': '20',
    'atts[columns]': '5',
    'atts[columns_tablet]': '3',
    'atts[columns_mobile]': '2',
    'atts[sale_countdown]': '0',
    'atts[stretch_product_desktop]': '0',
    'atts[stretch_product_tablet]': '0',
    'atts[stretch_product_mobile]': '0',
    'atts[stock_progress_bar]': '0',
    'atts[highlighted_products]': '0',
    'atts[products_bordered_grid]': '0',
    'atts[products_bordered_grid_style]': 'outside',
    'atts[products_with_background]': '0',
    'atts[products_shadow]': '0',
    'atts[products_color_scheme]': 'default',
    'atts[product_quantity]': '0',
    'atts[grid_gallery]': '',
    'atts[grid_gallery_control]': '',
    'atts[grid_gallery_enable_arrows]': '',
    'atts[offset]': '',
    'atts[orderby]': 'date',
    'atts[query_type]': 'OR',
    'atts[order]': 'DESC',
    'atts[meta_key]': '',
    'atts[exclude]': '',
    'atts[class]': '',
    'atts[ajax_page]': '',
    'atts[speed]': '5000',
    'atts[slides_per_view]': '4',
    'atts[slides_per_view_tablet]': 'auto',
    'atts[slides_per_view_mobile]': 'auto',
    'atts[wrap]': '',
    'atts[autoplay]': 'no',
    'atts[center_mode]': 'no',
    'atts[hide_pagination_control]': '',
    'atts[hide_prev_next_buttons]': '',
    'atts[scroll_per_page]': 'yes',
    'atts[img_size]': 'woocommerce_thumbnail',
    'atts[force_not_ajax]': 'no',
    'atts[products_masonry]': '0',
    'atts[products_different_sizes]': '0',
    'atts[lazy_loading]': 'yes',
    'atts[scroll_carousel_init]': 'no',
    'atts[el_class]': '',
    'atts[shop_tools]': 'no',
    'atts[query_post_type]': 'product',
    'atts[hide_out_of_stock]': 'no',
    'atts[css]': '',
    'atts[woodmart_css_id]': '6460f6a67ace8',
    'atts[ajax_recently_viewed]': 'no',
    'atts[is_wishlist]': '',
    'paged': '3',
    'action': 'woodmart_get_products_shortcode',
    'woo_ajax': '1',
}